### ISSUE TITLE
Could not find an overload of '-=' ...

### ISSUE THREAD

**Issue by tattooedpierre** [stephen-squidink/SpriteKit-Swift#1]
In the `GameScene.swift` file, running Mavericks  with Xcode6-Beta I get the build error:

```
Could not find an overload for '-=' that accepts the supplied arguments
```

Due to the code;

```
self.position.x -= self.parallaxSpeed;
```

**Comment by stephen-squidink** [comment]
I'm running Mavericks 10.9.3 and Xcode 6 Beta, that code segment is in the ParallaxSprite.swift file in the update. I'm not getting that error, will have a look into it though. 

I have seen that happen before, but I think it was Xcode being really buggy, I don't if it happens with everyone else, but if you select the GameScene.sks file, it completely freezes your machine and forces a reboot. Then you can never reopen the project because Xcode is trying to be clever by remembering the last file viewed and tries to reopen it.

**Comment by tattooedpierre** [comment]
I think you may be right. When I click on the GamScene.sks, as you say, my Xcode crashes. Thanks for this source code in any case. Helping me get into Swift/iPhone dev :)

**Comment by stephen-squidink** [comment]
Yea, no worries, hoping to add more, but its a start with Swift and SpriteKit ... :)
